package ChoiceLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class Choice_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    if (SPropertyOperations.getBoolean(node, MetaAdapterFactory.getProperty(0xa92e5bf9eea84a4cL, 0x99848f946109148dL, 0x5677359a7e047e87L, 0x5677359a7e048297L, "dimension")) == true) {
      appendNode(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xa92e5bf9eea84a4cL, 0x99848f946109148dL, 0x5677359a7e047e87L, 0x5677359a7e048285L, "alt1")));
    } else {
      appendNode(SLinkOperations.getTarget(node, MetaAdapterFactory.getContainmentLink(0xa92e5bf9eea84a4cL, 0x99848f946109148dL, 0x5677359a7e047e87L, 0x5677359a7e04828fL, "alt2")));
    }
  }
}
