package ChoiceLanguage.refactorings;

/*Generated by MPS */

import jetbrains.mps.refactoring.framework.IRefactoringTarget;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class ChangeState_Target implements IRefactoringTarget {
  public ChangeState_Target() {
  }
  public IRefactoringTarget.TargetType getTarget() {
    return IRefactoringTarget.TargetType.NODE;
  }
  public boolean allowMultipleTargets() {
    return false;
  }
  public boolean isApplicableToEntityType(final Object entity) {
    return SNodeOperations.isInstanceOf(((SNode) entity), MetaAdapterFactory.getInterfaceConcept(0xa92e5bf9eea84a4cL, 0x99848f946109148dL, 0x38b572bec4972be3L, "ChoiceLanguage.structure.IState"));
  }
  public boolean isApplicable(final Object entity) {
    if (!(this.isApplicableToEntityType(entity))) {
      return false;
    }
    return true;
  }
}
