package ChoiceLanguage.behavior;

/*Generated by MPS */


public class One_BehaviorDescriptor extends Variational_BehaviorDescriptor {
  public One_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.One";
  }
}
