package ChoiceLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public abstract class Variational_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public Variational_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.Variational";
  }
}
