package ChoiceLanguage.behavior;

/*Generated by MPS */


public class Alternative_BehaviorDescriptor extends Variational_BehaviorDescriptor {
  public Alternative_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.Alternative";
  }
}
