package ChoiceLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class ChoiceReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public ChoiceReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.ChoiceReference";
  }
}
