package ChoiceLanguage.behavior;

/*Generated by MPS */


public class Choice_BehaviorDescriptor extends Variational_BehaviorDescriptor {
  public Choice_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.Choice";
  }
}
