package ChoiceLanguage.behavior;

/*Generated by MPS */


public class Constant_BehaviorDescriptor extends Variational_BehaviorDescriptor {
  public Constant_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.Constant";
  }
}
