package ChoiceLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class Select_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public Select_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ChoiceLanguage.structure.Select";
  }
}
